CREATE TABLE IF NOT EXISTS users
(user_id INTEGER PRIMARY KEY NOT NULL, username TEXT, reg_date TEXT, notify TEXT);
CREATE TABLE IF NOT EXISTS currency_rub
(id INTEGER PRIMARY KEY, USD REAL,CAD REAL,AUD REAL,EUR REAL,GBP REAL,CHF REAL,
JPY REAL,ILS REAL,PLN REAL,UAH REAL,BITCOIN REAL, datetime TEXT);

